# =============================================================================
# UI.PY - YOLO Object Detection & Tracking GUI Application
# =============================================================================
# This file contains a complete PyQt5 application for:
# 1. Real-time object detection from video files
# 2. Analysis of CSV log files from detection runs
# 3. Visualization of statistics (charts, heatmaps, trajectories)
# =============================================================================

# -----------------------------------------------------------------------------
# LEVEL 1: EXTERNAL LIBRARY IMPORTS
# -----------------------------------------------------------------------------
import os          # File system operations (path validation, file size)
import csv         # CSV reading/writing for log files
import glob        # File pattern matching (globbing *.csv files)
import math        # Math operations (isfinite for security checks)
from collections import defaultdict, Counter  # Data structures for aggregation

# -----------------------------------------------------------------------------
# LEVEL 2: PyQt5 FRAMEWORK IMPORTS
# -----------------------------------------------------------------------------
# Qt Widgets - GUI components
from PyQt5.QtWidgets import (
    QWidget, QLabel, QPushButton, QComboBox, QListWidget,
    QVBoxLayout, QHBoxLayout, QGridLayout, QFrame, QFileDialog,
    QTableWidget, QTableWidgetItem, QHeaderView,
    QTabWidget, QCheckBox, QScrollArea, QGroupBox,
    QSizePolicy, QProgressBar, QAbstractItemView, QSlider,
    QMessageBox
)
# Qt Core - Constants and geometry
from PyQt5.QtCore import Qt, QRectF
# Qt GUI - Graphics and painting
from PyQt5.QtGui import (
    QColor, QFont, QPainter, QPen, QBrush,
    QLinearGradient, QPainterPath
)

# -----------------------------------------------------------------------------
# LEVEL 3: SECURITY CONSTANTS - Limits to prevent crashes and memory issues
# -----------------------------------------------------------------------------
# Maximum CSV file size accepted for analysis (50 MB).
# Prevents memory exhaustion from arbitrarily large files.
MAX_CSV_BYTES = 50 * 1024 * 1024   # 50 MB

# Maximum rows loaded into the results table.
# Even if the CSV has millions of rows the table only shows this many.
MAX_TABLE_ROWS = 10_000

# Expected CSV columns — used to validate that the file is actually a log
# generated by this application and not an arbitrary CSV.
EXPECTED_COLUMNS = {
    "video", "frame_id", "timestamp", "track_id", "class",
    "x1", "y1", "x2", "y2", "width", "height", "cx", "cy",
    "confidence", "direction", "event"
}

# Allowed values for the "class" column — prevents garbage data from
# polluting the analysis charts.
KNOWN_CLASSES = {"car", "bus", "truck", "motorcycle", "bicycle", "person"}

# Allowed values for the "direction" column.
KNOWN_DIRECTIONS = {"UP", "DOWN", "NONE", ""}

# Allowed values for the "event" column.
KNOWN_EVENTS = {"entry", "exit", "none", ""}


# -----------------------------------------------------------------------------
# LEVEL 4: DESIGN TOKENS - Color palette for object classes
# -----------------------------------------------------------------------------
# Clean light SaaS aesthetic (Notion × Linear × Vercel)
CLASS_PALETTE = {
    "car":        "#2563eb",  # Blue
    "bus":        "#7c3aed",  # Purple
    "truck":      "#0891b2",  # Cyan
    "motorcycle": "#ea580c",  # Orange
    "bicycle":    "#16a34a",  # Green
    "person":     "#db2777",  # Pink
    "ALL":        "#6b7280",  # Gray
}


# -----------------------------------------------------------------------------
# LEVEL 5: SECURITY HELPER FUNCTIONS - Safe input validation
# -----------------------------------------------------------------------------
def _safe_float(val: str, lo: float = -1e6, hi: float = 1e6,
                default: float = 0.0) -> float:
    """
    SECURITY FIX — safe numeric conversion.
    Parse val as float and clamp it to [lo, hi].
    Returns default on any parse error or if the value is NaN / Inf.
    Prevents chart rendering crashes from malformed CSV values.
    """
    try:
        f = float(val)
        if not math.isfinite(f):
            return default
        return max(lo, min(hi, f))
    except (ValueError, TypeError):
        return default


def _safe_int(val: str, lo: int = 0, hi: int = 10_000_000,
              default: int = 0) -> int:
    """SECURITY FIX — safe integer conversion with bounds."""
    try:
        return max(lo, min(hi, int(val)))
    except (ValueError, TypeError):
        return default


def _sanitise_cell(val: str, max_len: int = 256) -> str:
    """
    SECURITY FIX — truncate and strip control characters from CSV cell values
    before displaying them in the QTableWidget.
    """
    val = str(val)[:max_len]
    # Remove ASCII control characters (except tab/newline which str() handles)
    val = "".join(ch for ch in val if ch >= " " or ch in "\t\n")
    return val


# =============================================================================
# CUSTOM GRAPHICAL WIDGETS
# =============================================================================

# -----------------------------------------------------------------------------
# LEVEL 6: MiniBarChart - Vertical bar chart widget
# -----------------------------------------------------------------------------
class MiniBarChart(QWidget):
    """
    Custom widget for displaying vertical bar charts.
    Used for class distribution, direction split, and confidence charts.
    """
    
    def __init__(self, parent=None):
        super().__init__(parent)
        self._labels = []    # X-axis labels
        self._values = []    # Bar values
        self._colors = []    # Bar colors
        self.setMinimumHeight(170)

    def set_data(self, labels, values, colors=None):
        """Set chart data and trigger redraw."""
        self._labels = labels
        self._values = values
        self._colors = colors or ["#2563eb"] * len(labels)
        self.update()  # Trigger paintEvent

    def paintEvent(self, _):
        """
        Main drawing method - called automatically by Qt.
        Draws a bar chart with:
        - Background grid (horizontal lines)
        - Vertical scale (values)
        - Gradient-filled bars with rounded corners
        - Labels below each bar
        """
        if not self._values:
            return
        p = QPainter(self)
        p.setRenderHint(QPainter.Antialiasing)  # Edge smoothing
        W, H = self.width(), self.height()
        # Margins: PL=left, PR=right, PT=top, PB=bottom
        PL, PR, PT, PB = 42, 12, 20, 32
        dw = W - PL - PR
        dh = H - PT - PB
        mx = max(self._values) or 1
        n  = len(self._values)
        gap = 8
        bw  = max(10, (dw - gap * (n + 1)) // n)

        # Draw grid (5 horizontal lines)
        p.setPen(QPen(QColor("#f3f4f6"), 1))
        for i in range(5):
            y = PT + dh * i // 4
            p.drawLine(PL, y, W - PR, y)

        # Draw vertical scale
        p.setPen(QColor("#9ca3af"))
        p.setFont(QFont("Segoe UI", 8))
        for i in range(5):
            v = mx * (4 - i) / 4
            y = PT + dh * i // 4
            p.drawText(0, y - 6, PL - 4, 14, Qt.AlignRight, str(int(v)))

        # Draw bars
        for i, (lbl, val, col) in enumerate(
                zip(self._labels, self._values, self._colors)):
            x  = PL + gap + i * (bw + gap)
            bh = int(dh * val / mx)           # Proportional height
            y  = PT + dh - bh                  # Y position (bottom-up)
            
            # Gradient color for bar
            grad = QLinearGradient(x, y, x, y + bh)
            grad.setColorAt(0, QColor(col))
            c2 = QColor(col); c2.setAlpha(140)
            grad.setColorAt(1, c2)
            p.setBrush(QBrush(grad))
            p.setPen(Qt.NoPen)
            
            # Rounded rectangle bar
            path = QPainterPath()
            path.addRoundedRect(QRectF(x, y, bw, bh), 4, 4)
            p.drawPath(path)

            # Value above bar
            p.setPen(QColor("#374151"))
            p.setFont(QFont("Segoe UI", 8, QFont.Bold))
            p.drawText(x, max(4, y - 16), bw, 14, Qt.AlignCenter, str(val))

            # Label below bar
            p.setPen(QColor("#6b7280"))
            p.setFont(QFont("Segoe UI", 7))
            p.drawText(x - 4, H - PB + 6, bw + 8, 20,
                       Qt.AlignCenter, lbl[:7])
        p.end()


# -----------------------------------------------------------------------------
# LEVEL 7: MiniPieChart - Pie/donut chart widget
# -----------------------------------------------------------------------------
class MiniPieChart(QWidget):
    """
    Custom widget for displaying pie charts.
    Used for traffic mix visualization.
    """
    
    def __init__(self, parent=None):
        super().__init__(parent)
        self._labels = []
        self._values = []
        self._colors = []
        self.setMinimumSize(210, 180)

    def set_data(self, labels, values, colors=None):
        self._labels = labels
        self._values = values
        self._colors = colors or list(CLASS_PALETTE.values())
        self.update()

    def paintEvent(self, _):
        """
        Draws a pie chart with:
        - Colored sectors proportional to values
        - White borders between sectors
        - Legend with percentages on the right
        """
        if not self._values:
            return
        p = QPainter(self)
        p.setRenderHint(QPainter.Antialiasing)
        W, H   = self.width(), self.height()
        total  = sum(self._values) or 1
        r      = min(W // 2, H) // 2 - 14    # Circle radius
        cx, cy = r + 14, H // 2              # Circle center

        # Draw sectors
        angle = -90 * 16                      # Start angle (in 1/16 degree units)
        for i, (lbl, val) in enumerate(zip(self._labels, self._values)):
            span = int(360 * 16 * val / total)  # Sector angle
            p.setBrush(QBrush(QColor(self._colors[i % len(self._colors)])))
            p.setPen(QPen(QColor("#ffffff"), 2))  # White border between sectors
            p.drawPie(cx - r, cy - r, 2*r, 2*r, angle, span)
            angle += span

        # Draw legend
        lx = cx + r + 16
        ly = cy - len(self._labels) * 11
        p.setFont(QFont("Segoe UI", 8))
        for i, (lbl, val) in enumerate(zip(self._labels, self._values)):
            col = QColor(self._colors[i % len(self._colors)])
            p.setBrush(QBrush(col)); p.setPen(Qt.NoPen)
            p.drawRoundedRect(lx, ly + i * 20, 10, 10, 2, 2)  # Color square
            p.setPen(QColor("#374151"))
            pct = f"{100*val/total:.0f}%"
            p.drawText(lx + 14, ly + i * 20, 110, 14,
                       Qt.AlignLeft | Qt.AlignVCenter, f"{lbl}  {pct}")
        p.end()


# -----------------------------------------------------------------------------
# LEVEL 8: HeatmapWidget - Spatial heat map (22x22 grid)
# -----------------------------------------------------------------------------
class HeatmapWidget(QWidget):
    """
    Displays a 22x22 spatial heatmap of detected object positions.
    Color coding: dark blue (<33%) → cyan (33-66%) → green (>66%)
    """
    G = 22  # Grid size (22x22 cells)

    def __init__(self, parent=None):
        super().__init__(parent)
        self._grid = [[0]*self.G for _ in range(self.G)]  # 2D count grid
        self._max  = 1
        self.setMinimumSize(260, 190)

    def set_points(self, points, w=640, h=480):
        """
        Convert (cx, cy) coordinates to grid cell positions.
        For each point, increment the corresponding grid cell.
        """
        G = self.G
        self._grid = [[0]*G for _ in range(G)]
        for cx, cy in points:
            gi = min(G-1, max(0, int(cx * G / w)))  # Column index
            gj = min(G-1, max(0, int(cy * G / h)))  # Row index
            self._grid[gj][gi] += 1
        self._max = max(max(row) for row in self._grid) or 1
        self.update()

    def paintEvent(self, _):
        """
        Draws the heatmap with color gradient based on density:
        - Blue (< 33%): low density
        - Cyan (33-66%): medium density
        - Green (> 66%): high density
        Opacity increases with density.
        """
        p = QPainter(self)
        p.setRenderHint(QPainter.Antialiasing)
        W, H = self.width(), self.height()
        G    = self.G
        cw, ch = W/G, H/G
        
        # Black background
        p.fillRect(0, 0, W, H, QColor("#111827"))
        p.setPen(QPen(QColor(255,255,255,10), 1))
        
        # Grid lines
        for i in range(G+1):
            p.drawLine(int(i*cw), 0, int(i*cw), H)
            p.drawLine(0, int(i*ch), W, int(i*ch))
        
        # Colored cells
        for j in range(G):
            for i in range(G):
                ratio = self._grid[j][i] / self._max
                if ratio < 0.001:
                    continue
                if ratio < 0.33:
                    t = ratio / 0.33
                    r,g,b = 0, int(100+t*155), int(200+t*55)
                elif ratio < 0.66:
                    t = (ratio-0.33)/0.33
                    r,g,b = int(t*255), 255, int(255-t*255)
                else:
                    t = (ratio-0.66)/0.34
                    r,g,b = 255, int(255-t*255), 0
                alpha = min(255, int(ratio * 240))
                p.fillRect(int(i*cw), int(j*ch),
                           int(cw)+1, int(ch)+1, QColor(r, g, b, alpha))
        p.end()


# -----------------------------------------------------------------------------
# LEVEL 9: TrajectoryCanvas - Object trajectory visualization
# -----------------------------------------------------------------------------
class TrajectoryCanvas(QWidget):
    """
    Displays movement trajectories of tracked objects.
    Each trajectory shows:
    - Progressive line with increasing opacity
    - Final position marked with a circle (head)
    """
    
    def __init__(self, parent=None):
        super().__init__(parent)
        self._tracks = {}  # {track_id: {"cls": class, "points": [(x,y), ...]}}
        self.setMinimumSize(260, 190)

    def set_tracks(self, tracks):
        self._tracks = tracks
        self.update()

    def paintEvent(self, _):
        """
        Draws each trajectory:
        - Progressive line with increasing opacity toward the end
        - Final point (head) marked with a colored circle
        """
        p = QPainter(self)
        p.setRenderHint(QPainter.Antialiasing)
        W, H = self.width(), self.height()
        p.fillRect(0, 0, W, H, QColor("#111827"))
        
        # Background grid
        p.setPen(QPen(QColor(255,255,255,10), 1))
        for i in range(0, W, 30):
            p.drawLine(i, 0, i, H)
        for j in range(0, H, 30):
            p.drawLine(0, j, W, j)
        
        # Trajectories
        for tid, info in self._tracks.items():
            pts = info.get("points", [])
            if len(pts) < 2:
                continue
            col = QColor(CLASS_PALETTE.get(info.get("cls","car"), "#6b7280"))
            for k in range(1, len(pts)):
                alpha = int(60 + 195 * k / len(pts))  # Increasing opacity
                pen   = QPen(QColor(col.red(), col.green(), col.blue(), alpha), 1)
                p.setPen(pen)
                x0, y0 = pts[k-1]
                x1, y1 = pts[k]
                # Scale from 640x480 to widget size
                p.drawLine(int(x0*W/640), int(y0*H/480),
                           int(x1*W/640), int(y1*H/480))
            
            # Final point (trajectory head)
            lx, ly = pts[-1]
            p.setBrush(QBrush(col))
            p.setPen(QPen(QColor("#ffffff"), 1))
            p.drawEllipse(int(lx*W/640)-3, int(ly*H/480)-3, 6, 6)
        p.end()


# -----------------------------------------------------------------------------
# LEVEL 10: StatCard - Reusable statistics card widget
# -----------------------------------------------------------------------------
CARD_THEMES = {
    "blue":   ("#eff6ff","#bfdbfe","#1d4ed8","#2563eb"),
    "green":  ("#f0fdf4","#bbf7d0","#15803d","#16a34a"),
    "red":    ("#fef2f2","#fecaca","#b91c1c","#dc2626"),
    "amber":  ("#fffbeb","#fde68a","#92400e","#d97706"),
    "purple": ("#faf5ff","#e9d5ff","#6d28d9","#7c3aed"),
    "slate":  ("#f8fafc","#e2e8f0","#334155","#475569"),
}

class StatCard(QFrame):
    """
    Reusable statistics card widget.
    Displays an icon, title, and value with a color theme.
    """
    def __init__(self, icon, title, value="—", variant="slate", parent=None):
        super().__init__(parent)
        bg, border, txt, accent = CARD_THEMES.get(variant, CARD_THEMES["slate"])
        self.setStyleSheet(
            f"QFrame{{background:{bg};border:1px solid {border};"
            f"border-radius:10px;}}"
        )
        self.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        self.setFixedHeight(88)
        
        # Main layout
        lay = QVBoxLayout(self)
        lay.setContentsMargins(14, 11, 14, 11)
        lay.setSpacing(3)
        
        # Top row: icon + title
        top = QHBoxLayout()
        ico = QLabel(icon)
        ico.setStyleSheet(
            f"font-size:16px;background:{accent}22;"
            f"border-radius:6px;padding:4px 6px;color:{accent};"
        )
        ico.setFixedSize(32, 32); ico.setAlignment(Qt.AlignCenter)
        ttl = QLabel(title.upper())
        ttl.setStyleSheet(
            f"font-size:10px;font-weight:600;"
            f"letter-spacing:0.8px;color:{txt}88;"
        )
        top.addWidget(ico); top.addSpacing(6); top.addWidget(ttl); top.addStretch()
        
        # Main value
        self._val = QLabel(str(value))
        self._val.setStyleSheet(f"font-size:24px;font-weight:700;color:{txt};")
        lay.addLayout(top); lay.addWidget(self._val)

    def set_value(self, v):
        """Update the displayed value."""
        self._val.setText(str(v))


def chart_card(title, widget):
    """Create a framed container for a chart with title."""
    frame = QFrame()
    frame.setStyleSheet(
        "QFrame{background:#ffffff;border:1px solid #e5e7ef;border-radius:10px;}"
    )
    lay = QVBoxLayout(frame)
    lay.setContentsMargins(14, 12, 14, 12)
    if title:
        lbl = QLabel(title)
        lbl.setStyleSheet(
            "font-size:12px;font-weight:600;color:#374151;border:none;"
        )
        lay.addWidget(lbl)
    lay.addWidget(widget)
    return frame


# =============================================================================
# LEVEL 11: LogAnalysisPanel - CSV log analysis panel
# =============================================================================
class LogAnalysisPanel(QWidget):
    """
    Main panel for analyzing CSV log files.
    Allows importing logs, filtering by class, and visualizing statistics.
    """
    
    def __init__(self, parent=None):
        super().__init__(parent)
        self._filtered_rows = []  # Filtered data for export
        self._build_ui()

    def _build_ui(self):
        """Build the analysis panel UI."""
        root = QVBoxLayout(self)
        root.setContentsMargins(22, 20, 22, 20)
        root.setSpacing(16)

        # --- Header ---
        row = QHBoxLayout()
        h = QLabel("Log Analysis")
        h.setStyleSheet("font-size:20px;font-weight:700;color:#111827;")
        s = QLabel("Import CSV logs, filter by class, and explore insights")
        s.setStyleSheet("font-size:13px;color:#6b7280;")
        row.addWidget(h); row.addSpacing(14); row.addWidget(s); row.addStretch()
        root.addLayout(row)
        
        # Divider
        div = QFrame(); div.setFrameShape(QFrame.HLine)
        div.setStyleSheet("color:#e5e7ef;"); root.addWidget(div)

        # --- File picker + Class filter ---
        top = QHBoxLayout(); top.setSpacing(14)
        
        # Group: CSV file list
        fg = QGroupBox("Log Files")
        fl = QVBoxLayout(fg); fl.setSpacing(8)
        self.log_list = QListWidget()
        self.log_list.setSelectionMode(QAbstractItemView.ExtendedSelection)
        self.log_list.setFixedHeight(118)
        
        # Action buttons
        br = QHBoxLayout(); br.setSpacing(8)
        self.btn_add    = QPushButton("＋  Add Files")
        self.btn_folder = QPushButton("📁  Folder")
        self.btn_clear  = QPushButton("✕  Clear")
        self.btn_clear.setStyleSheet(
            "QPushButton{color:#dc2626;border-color:#fecaca;background:#fef2f2;}"
            "QPushButton:hover{background:#fee2e2;}"
        )
        for b in (self.btn_add, self.btn_folder, self.btn_clear):
            b.setFixedHeight(30); br.addWidget(b)
        fl.addWidget(self.log_list); fl.addLayout(br)
        top.addWidget(fg, stretch=1)

        # Group: Class filter checkboxes
        cg = QGroupBox("Class Filter")
        cl = QVBoxLayout(cg); cl.setSpacing(6); cg.setFixedWidth(166)
        self._checks = {}
        for cls in ["ALL","car","bus","truck","motorcycle","bicycle","person"]:
            cb = QCheckBox(cls.capitalize())
            col = CLASS_PALETTE.get(cls, "#6b7280")
            cb.setStyleSheet(
                f"QCheckBox{{color:{col};font-weight:500;}}"
                f"QCheckBox::indicator:checked{{background:{col};"
                f"border-color:{col};}}"
            )
            cb.setChecked(True)
            self._checks[cls] = cb
            if cls == "ALL":
                cb.stateChanged.connect(self._toggle_all)
            cl.addWidget(cb)
        cl.addStretch(); top.addWidget(cg)
        root.addLayout(top)

        # --- Run button + Status ---
        ar = QHBoxLayout(); ar.setSpacing(14)
        self.btn_analyse = QPushButton("▶  Run Analysis")
        self.btn_analyse.setObjectName("btn_analyse")
        self.btn_analyse.setFixedHeight(40); self.btn_analyse.setFixedWidth(176)
        self.status_lbl = QLabel("Ready — add CSV log files to begin.")
        self.status_lbl.setStyleSheet("color:#6b7280;font-size:12px;")
        ar.addWidget(self.btn_analyse); ar.addSpacing(10)
        ar.addWidget(self.status_lbl, stretch=1)
        root.addLayout(ar)

        # Progress bar
        self.progress = QProgressBar()
        self.progress.setFixedHeight(6); self.progress.setValue(0)
        self.progress.setTextVisible(False); root.addWidget(self.progress)

        # --- Statistics cards ---
        cr = QHBoxLayout(); cr.setSpacing(10)
        self.c_files   = StatCard("📂","Files",  "0","slate")
        self.c_tracks  = StatCard("🔢","Tracks", "0","blue")
        self.c_frames  = StatCard("🎞","Frames", "0","purple")
        self.c_entries = StatCard("⬇","Entries","0","green")
        self.c_exits   = StatCard("⬆","Exits",  "0","red")
        self.c_net     = StatCard("≡","Net Flow","—","amber")
        for c in (self.c_files,self.c_tracks,self.c_frames,
                  self.c_entries,self.c_exits,self.c_net):
            cr.addWidget(c)
        root.addLayout(cr)

        # --- Charts row 1 ---
        r1 = QHBoxLayout(); r1.setSpacing(14)
        self.bar_chart = MiniBarChart()
        r1.addWidget(chart_card("Class Distribution", self.bar_chart), stretch=2)
        self.pie_chart = MiniPieChart()
        r1.addWidget(chart_card("Traffic Mix", self.pie_chart), stretch=1)
        self.dir_chart = MiniBarChart()
        r1.addWidget(chart_card("Direction Split (UP / DOWN)", self.dir_chart), stretch=1)
        root.addLayout(r1)

        # --- Charts row 2 ---
        r2 = QHBoxLayout(); r2.setSpacing(14)
        self.heatmap = HeatmapWidget()
        r2.addWidget(chart_card("Position Heatmap", self.heatmap), stretch=1)
        self.traj = TrajectoryCanvas()
        r2.addWidget(chart_card("Trajectory Map", self.traj), stretch=1)
        self.conf_chart = MiniBarChart()
        r2.addWidget(chart_card("Avg Confidence % by Class", self.conf_chart), stretch=1)
        root.addLayout(r2)

        # --- Data table ---
        tbl_grp = QGroupBox("Detection Records")
        tl = QVBoxLayout(tbl_grp)
        ex_row = QHBoxLayout(); ex_row.addStretch()
        self.btn_export = QPushButton("⬇  Export Filtered CSV")
        self.btn_export.setObjectName("btn_export")
        self.btn_export.setFixedHeight(30); self.btn_export.setEnabled(False)
        ex_row.addWidget(self.btn_export); tl.addLayout(ex_row)
        
        self.table = QTableWidget()
        self.table.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.table.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.table.setAlternatingRowColors(True)
        cols = ["File","Frame","Timestamp","Track","Class",
                "x1","y1","x2","y2","W","H","cx","cy",
                "Conf","Direction","Event"]
        self.table.setColumnCount(len(cols))
        self.table.setHorizontalHeaderLabels(cols)
        self.table.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeToContents)
        self.table.horizontalHeader().setStretchLastSection(True)
        self.table.setMinimumHeight(200)
        tl.addWidget(self.table); root.addWidget(tbl_grp)

        # Signal connections
        self.btn_add.clicked.connect(self._add_files)
        self.btn_folder.clicked.connect(self._add_folder)
        self.btn_clear.clicked.connect(self._clear_logs)
        self.btn_analyse.clicked.connect(self._run_analysis)
        self.btn_export.clicked.connect(self._export)

    # --- Helper methods ---
    
    def _toggle_all(self, state):
        """Check/uncheck all classes based on ALL checkbox state."""
        checked = (state == Qt.Checked)
        for name, cb in self._checks.items():
            if name != "ALL":
                cb.blockSignals(True); cb.setChecked(checked); cb.blockSignals(False)

    def _selected_classes(self):
        """Return set of checked classes."""
        return {n for n, cb in self._checks.items()
                if n != "ALL" and cb.isChecked()}

    def _exists(self, path):
        """Check if file is already in the list."""
        return any(self.log_list.item(i).text() == path
                   for i in range(self.log_list.count()))

    def _validate_csv_path(self, path: str) -> str | None:
        """
        Validate a CSV file path.
        Returns error message if invalid, None if OK.
        Checks: existence, .csv extension, size < MAX_CSV_BYTES
        """
        if not os.path.isfile(path):
            return f"Not a regular file: {os.path.basename(path)}"
        if not path.lower().endswith(".csv"):
            return f"Not a CSV file: {os.path.basename(path)}"
        size = os.path.getsize(path)
        if size > MAX_CSV_BYTES:
            mb = size / (1024*1024)
            return (f"{os.path.basename(path)} is {mb:.1f} MB "
                    f"(limit {MAX_CSV_BYTES//(1024*1024)} MB)")
        return None

    def _add_files(self):
        """Open file dialog to add CSV files."""
        files, _ = QFileDialog.getOpenFileNames(
            self, "Select Log CSV files", "", "CSV Files (*.csv);;All Files (*)")
        rejected = []
        for f in files:
            err = self._validate_csv_path(f)
            if err:
                rejected.append(err)
                continue
            if not self._exists(f):
                self.log_list.addItem(f)
        if rejected:
            QMessageBox.warning(self, "Files rejected",
                                "The following files were not added:\n\n"
                                + "\n".join(f"• {e}" for e in rejected))
        self.c_files.set_value(str(self.log_list.count()))

    def _add_folder(self):
        """Open folder dialog to add all CSV files from a directory."""
        folder = QFileDialog.getExistingDirectory(self, "Select Logs Folder")
        if folder:
            for f in sorted(glob.glob(os.path.join(folder, "*.csv"))):
                err = self._validate_csv_path(f)
                if err:
                    continue
                if not self._exists(f):
                    self.log_list.addItem(f)
        self.c_files.set_value(str(self.log_list.count()))

    def _clear_logs(self):
        """Clear all files from the list."""
        self.log_list.clear(); self.c_files.set_value("0")

    # --- Analysis ---
    
    def _run_analysis(self):
        """
        Analyze selected CSV files and update all charts.
        Steps:
        1. Validate files
        2. Read each CSV and extract data
        3. Aggregate by unique track
        4. Update stat cards, charts, and table
        """
        files = [self.log_list.item(i).text()
                 for i in range(self.log_list.count())]
        if not files:
            self.status_lbl.setText("⚠  No log files loaded."); return
        allowed = self._selected_classes()
        if not allowed:
            self.status_lbl.setText("⚠  No class selected."); return

        self.status_lbl.setText("Processing…")
        self.table.setRowCount(0); self.progress.setValue(0)

        all_rows   = []
        frames_set = set()
        track_meta = {}   # (fpath, tid) -> dict

        for fi, fpath in enumerate(files):
            # Re-validate at analysis time (file may have changed)
            err = self._validate_csv_path(fpath)
            if err:
                self.status_lbl.setText(f"⚠  Skipped: {err}")
                continue

            try:
                with open(fpath, newline="", encoding="utf-8",
                          errors="replace") as fh:
                    reader = csv.DictReader(fh)

                    # Validate CSV structure
                    if reader.fieldnames is None:
                        self.status_lbl.setText(
                            f"⚠  Empty or invalid CSV: {os.path.basename(fpath)}")
                        return
                    missing = EXPECTED_COLUMNS - set(reader.fieldnames)
                    if missing:
                        self.status_lbl.setText(
                            f"⚠  Missing columns in {os.path.basename(fpath)}: "
                            f"{', '.join(sorted(missing))}")
                        return

                    # Read rows
                    for row in reader:
                        # Validate class
                        cls = row.get("class", "").strip()
                        if cls not in KNOWN_CLASSES:
                            continue
                        if cls not in allowed:
                            continue

                        # Validate direction/event
                        direction = row.get("direction","").strip().upper()
                        if direction not in KNOWN_DIRECTIONS:
                            direction = "NONE"

                        evt = row.get("event","").strip().lower()
                        if evt not in KNOWN_EVENTS:
                            evt = "none"

                        # Safe coordinate conversion
                        cx   = _safe_float(row.get("cx",""),   0, 640)
                        cy   = _safe_float(row.get("cy",""),   0, 480)
                        conf = _safe_float(row.get("confidence",""), 0, 1)

                        # Sanitize row
                        clean_row = {k: _sanitise_cell(v)
                                     for k, v in row.items()}
                        clean_row["direction"] = direction
                        clean_row["event"]     = evt
                        clean_row["class"]     = cls

                        all_rows.append(clean_row)

                        # Track metadata
                        tid = row.get("track_id","").strip()
                        key = (fpath, tid)
                        frames_set.add((fpath, row.get("frame_id","")))

                        if key not in track_meta:
                            track_meta[key] = {
                                "cls": cls, "confs": [],
                                "dir_votes": Counter(),
                                "points": [], "entries": 0, "exits": 0,
                            }
                        tm = track_meta[key]
                        if conf > 0:
                            tm["confs"].append(conf)
                        if direction and direction != "NONE":
                            tm["dir_votes"][direction] += 1
                        if evt == "entry":  tm["entries"] += 1
                        elif evt == "exit": tm["exits"]   += 1
                        if cx > 0 or cy > 0:
                            tm["points"].append((cx, cy))

            except Exception as e:
                self.status_lbl.setText(
                    f"⚠  Error: {os.path.basename(fpath)}: {e}")
                return

            self.progress.setValue(int((fi+1)/len(files)*100))

        # --- Aggregate by unique track ---
        class_counts = Counter()
        class_conf   = defaultdict(list)
        dir_counts   = Counter()
        entries = exits = 0
        track_data = {}

        for key, tm in track_meta.items():
            cls = tm["cls"]
            class_counts[cls] += 1
            if tm["confs"]:
                class_conf[cls].append(sum(tm["confs"]) / len(tm["confs"]))
            if tm["dir_votes"]:
                dir_counts[tm["dir_votes"].most_common(1)[0][0]] += 1
            if tm["entries"] > 0: entries += 1
            if tm["exits"]   > 0: exits   += 1
            track_data[str(key)] = {"cls": cls, "points": tm["points"]}

        # --- Update table (capped at MAX_TABLE_ROWS) ---
        display_rows = all_rows[:MAX_TABLE_ROWS]
        self.table.setRowCount(len(display_rows))
        col_keys = ["video","frame_id","timestamp","track_id","class",
                    "x1","y1","x2","y2","width","height","cx","cy",
                    "confidence","direction","event"]
        for ri, row in enumerate(display_rows):
            for ci, col in enumerate(col_keys):
                val  = row.get(col, "")
                item = QTableWidgetItem(str(val))
                item.setTextAlignment(Qt.AlignCenter)
                evt = row.get("event","").strip().lower()
                if evt == "entry":  item.setForeground(QColor("#16a34a"))
                elif evt == "exit": item.setForeground(QColor("#dc2626"))
                if ci == 4:
                    item.setForeground(QColor(CLASS_PALETTE.get(val,"#374151")))
                self.table.setItem(ri, ci, item)

        # --- Update stat cards ---
        n_tracks = len(track_meta)
        self.c_files.set_value(str(len(files)))
        self.c_tracks.set_value(str(n_tracks))
        self.c_frames.set_value(str(len(frames_set)))
        self.c_entries.set_value(str(entries))
        self.c_exits.set_value(str(exits))
        net = entries - exits
        self.c_net.set_value(f"{net:+d}" if all_rows else "—")

        # --- Update charts ---
        order  = ["car","bus","truck","motorcycle","bicycle","person"]
        labels = [c for c in order if class_counts.get(c,0)>0]
        values = [class_counts[c] for c in labels]
        colors = [CLASS_PALETTE[c] for c in labels]
        self.bar_chart.set_data(labels, values, colors)
        self.pie_chart.set_data(labels, values, colors)

        dl = [k for k in ["UP","DOWN"] if dir_counts.get(k,0)>0]
        dv = [dir_counts[k] for k in dl]
        dc = ["#dc2626" if k=="UP" else "#2563eb" for k in dl]
        self.dir_chart.set_data(dl, dv, dc)

        # Points for heatmap
        pts = [(r_cx, r_cy)
               for row in all_rows
               for r_cx, r_cy in [(_safe_float(row.get("cx",""),0,640),
                                    _safe_float(row.get("cy",""),0,480))]
               if r_cx > 0 or r_cy > 0]
        self.heatmap.set_points(pts)
        self.traj.set_tracks(track_data)

        # Average confidence by class
        cl = [c for c in labels if class_conf.get(c)]
        cv = [round(sum(class_conf[c])/len(class_conf[c])*100) for c in cl]
        self.conf_chart.set_data(cl, cv, [CLASS_PALETTE[c] for c in cl])

        self._filtered_rows = all_rows
        self.btn_export.setEnabled(bool(all_rows))

        # Warning if truncated
        cap_note = ""
        if len(all_rows) > MAX_TABLE_ROWS:
            cap_note = f"  (table capped at {MAX_TABLE_ROWS:,} rows)"

        self.status_lbl.setText(
            f"✔  {n_tracks} unique objects · {len(frames_set)} frames "
            f"· {len(all_rows):,} records · {len(files)} file(s){cap_note}"
        )

    def _export(self):
        """Export filtered data to CSV file."""
        if not self._filtered_rows:
            return
        path, _ = QFileDialog.getSaveFileName(
            self, "Export CSV", "filtered_log.csv", "CSV Files (*.csv)")
        if not path:
            return
        if not path.lower().endswith(".csv"):
            path += ".csv"
        try:
            with open(path, "w", newline="", encoding="utf-8") as fh:
                w = csv.DictWriter(fh,
                                   fieldnames=self._filtered_rows[0].keys(),
                                   extrasaction="ignore")
                w.writeheader(); w.writerows(self._filtered_rows)
            self.status_lbl.setText(
                f"✔  Exported {len(self._filtered_rows):,} rows → {path}")
        except Exception as e:
            self.status_lbl.setText(f"⚠  Export error: {e}")


# ─────────────────────────────────────────────────────────────────────────────
#  MAIN UI
# ─────────────────────────────────────────────────────────────────────────────
class UI(QWidget):
    @staticmethod
    def load_stylesheet(path):
        with open(path, "r", encoding="utf-8") as f:
            return f.read()
    def __init__(self):
        super().__init__()
        self.setWindowTitle("YOLO Detection + Tracking")
        self.setMinimumSize(980, 700)
        # self.setStyleSheet(load_stylesheet("style.qss"))
        self.setStyleSheet(self.load_stylesheet("style.qss"))
        self._build_ui()

    def _build_ui(self):
        root = QVBoxLayout(self)
        root.setContentsMargins(0,0,0,0); root.setSpacing(0)

        # title bar
        tb = QFrame(); tb.setObjectName("titlebar"); tb.setFixedHeight(52)
        tbl = QHBoxLayout(tb); tbl.setContentsMargins(20,0,20,0)
        brand = QLabel("🎯  YOLO Tracker")
        brand.setStyleSheet("font-size:15px;font-weight:700;color:#111827;")
        tbl.addWidget(brand); tbl.addStretch()
        self.fps_label     = QLabel("FPS: —")
        self.counter_label = QLabel("Objects: 0")
        for lbl in (self.fps_label, self.counter_label):
            lbl.setStyleSheet(
                "color:#6b7280;font-size:12px;background:#f3f4f6;"
                "border:1px solid #e5e7ef;border-radius:5px;padding:3px 10px;"
            )
            tbl.addWidget(lbl); tbl.addSpacing(8)
        root.addWidget(tb)

        self.tabs = QTabWidget(); self.tabs.setDocumentMode(True)
        root.addWidget(self.tabs)

        # ── TAB 1 : Live Detection ─────────────────────────────────────────────
        live = QWidget()
        ll = QHBoxLayout(live)
        ll.setContentsMargins(16,16,16,16); ll.setSpacing(16)

        self.video = QLabel()
        self.video.setObjectName("video_label")
        self.video.setMinimumSize(640,480); self.video.setAlignment(Qt.AlignCenter)
        self.video.setText("No Signal")
        self.video.setStyleSheet(
            "QLabel#video_label{background:#111827;border-radius:10px;"
            "color:#4b5563;font-size:16px;font-weight:600;}")
        ll.addWidget(self.video, stretch=1)

        rp = QVBoxLayout(); rp.setSpacing(12)

        # source
        sg = QGroupBox("Video Source")
        sl = QVBoxLayout(sg); sl.setSpacing(8)
        self.select_btn = QPushButton("📂  Select Video File")
        self.select_btn.setFixedHeight(34)
        self.video_path_label = QLabel("No video selected")
        self.video_path_label.setWordWrap(True)
        self.video_path_label.setStyleSheet(
            "color:#6b7280;font-size:11px;background:#f9fafb;"
            "border:1px solid #e5e7ef;border-radius:6px;padding:6px 10px;"
        )
        sl.addWidget(self.select_btn); sl.addWidget(self.video_path_label)
        rp.addWidget(sg)

        # class filter (checkboxes)
        cg = QGroupBox("Class Filter")
        cgv = QVBoxLayout(cg); cgv.setSpacing(6)
        self._live_all_cb = QCheckBox("All classes")
        self._live_all_cb.setChecked(True)
        self._live_all_cb.setTristate(True)
        self._live_all_cb.setStyleSheet(
            "font-weight:600;color:#111827;"
            "QCheckBox::indicator:checked{background:#2563eb;border-color:#2563eb;}"
            "QCheckBox::indicator:indeterminate{background:#93c5fd;border-color:#2563eb;}"
        )
        cgv.addWidget(self._live_all_cb)
        sep2 = QFrame(); sep2.setFrameShape(QFrame.HLine)
        sep2.setStyleSheet("color:#e5e7ef;"); cgv.addWidget(sep2)
        grid = QGridLayout(); grid.setSpacing(4)
        self._live_class_cbs = {}
        for i, cls in enumerate(["car","bus","truck","motorcycle","bicycle","person"]):
            col_hex = CLASS_PALETTE.get(cls, "#6b7280")
            cb = QCheckBox(cls.capitalize()); cb.setChecked(True)
            cb.setStyleSheet(
                f"QCheckBox{{color:{col_hex};font-weight:500;}}"
                f"QCheckBox::indicator:checked{{background:{col_hex};"
                f"border-color:{col_hex};}}"
            )
            self._live_class_cbs[cls] = cb
            grid.addWidget(cb, i // 2, i % 2)
        cgv.addLayout(grid)
        self.class_select = QComboBox(); self.class_select.hide()
        self._live_all_cb.stateChanged.connect(self._on_live_all_toggled)
        for cb in self._live_class_cbs.values():
            cb.stateChanged.connect(self._on_live_class_toggled)
        rp.addWidget(cg)

        # controls
        ctg = QGroupBox("Controls")
        ctr = QGridLayout(ctg); ctr.setSpacing(8)
        self.start_btn = QPushButton("▶  Start")
        self.stop_btn  = QPushButton("■  Stop")
        self.pause_btn = QPushButton("⏸  Pause")
        self.start_btn.setObjectName("btn_start")
        self.stop_btn.setObjectName("btn_stop")
        self.pause_btn.setObjectName("btn_pause")
        for b in (self.start_btn, self.stop_btn, self.pause_btn):
            b.setFixedHeight(36)
        ctr.addWidget(self.start_btn, 0, 0, 1, 2)
        ctr.addWidget(self.pause_btn, 1, 0); ctr.addWidget(self.stop_btn, 1, 1)
        rp.addWidget(ctg)

        # live counts
        stg = QGroupBox("Live Counts")
        stl = QHBoxLayout(stg); stl.setSpacing(8)
        self._live_in  = StatCard("⬇","In",  "0","green")
        self._live_out = StatCard("⬆","Out", "0","red")
        self._live_net = StatCard("≡","Net", "—","amber")
        for c in (self._live_in, self._live_out, self._live_net):
            stl.addWidget(c)
        rp.addWidget(stg)

        # counting line slider
        line_grp = QGroupBox("Counting Line Position")
        line_lay = QVBoxLayout(line_grp); line_lay.setSpacing(6)
        line_top = QHBoxLayout()
        line_hint = QLabel("Set before Start — locked during playback")
        line_hint.setStyleSheet("color:#6b7280;font-size:11px;border:none;")
        self._line_y_label = QLabel("y = 240 px  (50%)")
        self._line_y_label.setStyleSheet(
            "color:#2563eb;font-size:11px;font-weight:600;border:none;")
        line_top.addWidget(line_hint); line_top.addStretch()
        line_top.addWidget(self._line_y_label)
        line_lay.addLayout(line_top)
        self.line_slider = QSlider(Qt.Horizontal)
        self.line_slider.setMinimum(10); self.line_slider.setMaximum(470)
        self.line_slider.setValue(240); self.line_slider.setTickInterval(46)
        self.line_slider.setTickPosition(QSlider.TicksBelow)
        self.line_slider.setStyleSheet("""
            QSlider::groove:horizontal {
                height: 5px; background: #e5e7ef; border-radius: 3px;
            }
            QSlider::handle:horizontal {
                background: #2563eb; border: 2px solid #ffffff;
                width: 16px; height: 16px; margin: -6px 0; border-radius: 8px;
            }
            QSlider::handle:horizontal:hover { background: #1d4ed8; }
            QSlider::sub-page:horizontal { background: #2563eb; border-radius: 3px; }
        """)
        line_lay.addWidget(self.line_slider)
        pct_row = QHBoxLayout()
        for pct in ["Top (0%)", "25%", "Mid (50%)", "75%", "Bot (100%)"]:
            lbl2 = QLabel(pct)
            lbl2.setStyleSheet("color:#9ca3af;font-size:9px;border:none;")
            lbl2.setAlignment(Qt.AlignCenter); pct_row.addWidget(lbl2)
        line_lay.addLayout(pct_row)
        self.line_slider.valueChanged.connect(self._on_line_slider_changed)
        rp.addWidget(line_grp)

        # events log
        lg = QGroupBox("Events")
        lgl = QVBoxLayout(lg)
        self.list_widget = QListWidget(); self.list_widget.setMaximumHeight(120)
        lgl.addWidget(self.list_widget); rp.addWidget(lg)

        rp.addStretch(); ll.addLayout(rp)
        self.tabs.addTab(live, "  Live Detection  ")

        # ── TAB 2 : Log Analysis ───────────────────────────────────────────────
        self.log_panel = LogAnalysisPanel()
        sc = QScrollArea(); sc.setWidgetResizable(True)
        sc.setWidget(self.log_panel)
        sc.setStyleSheet("QScrollArea{border:none;background:#f8f9fc;}")
        self.tabs.addTab(sc, "  Log Analysis  ")

    # ── live filter helpers ────────────────────────────────────────────────────
    def _on_live_all_toggled(self, state):
        checked = (state == Qt.Checked)
        for cb in self._live_class_cbs.values():
            cb.blockSignals(True); cb.setChecked(checked); cb.blockSignals(False)
        self._sync_class_select()

    def _on_live_class_toggled(self):
        all_checked = all(cb.isChecked() for cb in self._live_class_cbs.values())
        any_checked = any(cb.isChecked() for cb in self._live_class_cbs.values())
        self._live_all_cb.blockSignals(True)
        if all_checked:           self._live_all_cb.setCheckState(Qt.Checked)
        elif any_checked:         self._live_all_cb.setCheckState(Qt.PartiallyChecked)
        else:                     self._live_all_cb.setCheckState(Qt.Unchecked)
        self._live_all_cb.blockSignals(False)
        self._sync_class_select()

    def _sync_class_select(self):
        checked = [cls for cls, cb in self._live_class_cbs.items() if cb.isChecked()]
        if len(checked) == len(self._live_class_cbs) or len(checked) == 0:
            self.class_select.setCurrentText("ALL")
        elif len(checked) == 1:
            self.class_select.setCurrentText(checked[0])
        else:
            self.class_select.setCurrentText("ALL")

    def get_live_allowed_classes(self) -> list:
        checked = [cls for cls, cb in self._live_class_cbs.items()
                   if cb.isChecked()]
        return checked if checked else list(self._live_class_cbs.keys())

    def _on_line_slider_changed(self, value: int):
        pct = round((value - 10) / (470 - 10) * 100)
        self._line_y_label.setText(f"y = {value} px  ({pct}%)")

    def get_line_y(self) -> int:
        return self.line_slider.value()

    def set_live_counts(self, enters: int, exits: int):
        self._live_in.set_value(str(enters))
        self._live_out.set_value(str(exits))
        self._live_net.set_value(f"{enters - exits:+d}")
